/**
 * Created by jyothi on 30/4/17.
 */

export const GET_TODOS_PENDING = "GET_TODOS_PENDING";
export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";

export const ADD_TODO_PENDING = "ADD_TODO_PENDING";
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const UPDATE_TODO_PENDING = "UPDATE_TODO_PENDING";
export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED";

export const DELETE_TODO_PENDING = "DELETE_TODO_PENDING";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";

export const TODO_SUGGESTIONS_PENDING = "TODO_SUGGESTIONS_PENDING";
export const TODO_SUGGESTIONS = "TODO_SUGGESTIONS";
export const TODO_SUGGESTIONS_FAILED = "TODO_SUGGESTIONS_FAILED";